name: GoInvest
configs:
  Release: release
  Debug: debug
options:
  minimumXcodeGenVersion: 2.39.1
  deploymentTarget:
    iOS: 17.0
targets:
  GoInvest:
    type: application
    platform: iOS
    settings:
      base:
        MARKETING_VERSION: 1.0
    sources:
       - path: GoInvest/
