name: GoInvest
configs:
  Release: release
  Debug: debug
options:
  minimumXcodeGenVersion: 2.39.1
  deploymentTarget:
    iOS: 17.0
targets:
    GoInvest:
        type: application
        platform: iOS
        sources:
            - path: GoInvest/
        settings:
            base:
                PRODUCT_BUNDLE_IDENTIFIER: com.yandex.sirius.GoInvest
#        dependencies:
#        - framework: UIComponents.framework
        scheme:
            testTargets:
            - GoInvestTests
    GoInvestTests:
        type: bundle.unit-test
        platform: iOS
        sources:
            - path: GoInvestTests

