name: GoInvest
configs:
  Release: release
  Debug: debug
options:
  minimumXcodeGenVersion: 2.39.1
  deploymentTarget:
    iOS: 16.0
targets:
    GoInvest:
        type: application
        platform: iOS
        sources:
            - path: GoInvest/
        settings:
            base:
                PRODUCT_BUNDLE_IDENTIFIER: com.shares.GoInvest
        scheme:
            testTargets:
            - GoInvestTests
        preBuildScripts:
            - script: |
                #!/bin/bash
                # Swiftlint
    
                export PATH="$PATH:/opt/homebrew/bin"
                if which swiftlint >/dev/null; then
                    swiftlint lint --strict
                else
                    echo "error: SwiftLint does not exist, download it from https://github.com/realm/SwiftLint"
                    exit 1
                fi
            - script: |
                #!/bin/bash
                "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
                echo $DWARF_DSYM_FILE_NAME
            - inputFiles:
                - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}
                - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${PRODUCT_NAME}
                - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Info.plist
                - $(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist
                - $(TARGET_BUILD_DIR)/$(EXECUTABLE_PATH)
    GoInvestTests:
        type: bundle.unit-test
        platform: iOS
        sources:
            - path: GoInvestTests
        settings:
            base:
                PRODUCT_BUNDLE_IDENTIFIER: com.yandex.sirius.GoInvestTest
                GENERATE_INFOPLIST_FILE: YES
