name: GoInvest
configs:
  Release: release
  Debug: debug
options:
  minimumXcodeGenVersion: 2.39.1
  deploymentTarget:
    iOS: 17.0
targets:
    GoInvest:
        type: application
        platform: iOS
        sources:
            - path: GoInvest/
        settings:
            base:
                PRODUCT_BUNDLE_IDENTIFIER: com.yandex.sirius.GoInvest
        scheme:
            testTargets:
            - GoInvestTests
        preBuildScripts:
            - script: |
                #!/bin/bash
                # Swiftlint
    
                export PATH="$PATH:/opt/homebrew/bin"
                echo "sdfdsfsdfdsf"
                if which swiftlint >/dev/null; then
                    swiftlint lint --strict
                else
                    echo "error: SwiftLint does not exist, download it from https://github.com/realm/SwiftLint"
                    exit 1
                fi
                
                
    GoInvestTests:
        type: bundle.unit-test
        platform: iOS
        sources:
            - path: GoInvestTests
