#!/bin/bash

# Запускаем SwiftLint
 

if which swiftlint > /dev/null; then
  # Проверяем наличие предупреждений
  swiftlint --fix
  if ! swiftlint | grep -q "warning" &&  ! swiftlint | grep -q "error"; then
    echo "✅ Linting successed"
  else
    swiftlint
    echo "❌ SwiftLint warnings found. Commit aborted."
    exit 1  # Прерываем коммит
  fi
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi