# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "**" ]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SwiftLint
        run: |
          brew install swiftlint
          swiftlint lint --config .swiftlint.yml --strict
  build:
  
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    # - name: Install Dependencies
    #   run: |
    #       brew install swiftlint

    # - name: Fail if SwiftLint Warnings
    #   run: |
    #       swiftlint lint --config .swiftlint.yml --strict
    
    - name: Install XcodeGen
      run: |
        brew update
        brew install xcodegen

    - name: Generate Xcode project
      run: |
        xcodegen generate
      shell: bash

    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash

    - name: Build
      run: |
        xcodebuild build -workspace GoInvest.xcworkspace -scheme GoInvest clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

    # - name: Run tests
    #   run: |
    #     xcodebuild test -workspace GoInvest.xcworkspace -scheme GoInvest clean build -sdk iphoneos -destination "platform=iOS Simulator,name=iPhone 14 Plus" CODE_SIGNING_ALLOWED=No
