# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "**" ]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
  build:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash
      
    - name: Install XcodeGen
      run: |
        brew update
        brew install xcodegen

    - name: Generate Xcode project
      run: |
        xcodegen generate
      shell: bash
      
    - name: Build
      run: |
        xcodebuild build -workspace GoInvest.xcworkspace -scheme GoInvest clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No
    #   run: |
    #        xcodebuild clean test -workspace "GoInvest/GoInvest.xcworkspace" -scheme "GoInvest" -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
